arm_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - D1
    - D2
    - D3
    - D4
  gains:
    D1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    D2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    D3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    D4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1