controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - D1
      - D2
      - D3
      - D4
  - name: fake_gripper_group_controller
    type: $(arg fake_execution_type)
    joints:
      - D4
      - Slider_5
      - Slider_6
initial:  # Define initial robot poses per group
  - group: arm_group
    pose: default